### ISSUE TITLE
isLoading state async function

### ISSUE THREAD

**Issue by DistroDan** [ReactComponentKit/Redux#10]
Hello. Awesome library. I love how simple it is to use for state management. One question I have is how you'd go about a isLoading state? I'd like to use loading state to display a spinner to show that an action is loading when a button is pressed. In my store I've created the following 
` @Published
    var isLoading: Bool = false`
which has a mutation 
`private func SET_LOADING(authState: inout AuthState, payload: Bool) {
        authState.isLoading = payload
    }`
I currently have an async function that signs a user in using an action and commiting the result which works perfectly. When I try to change the loading status though using the state it is not reflected. Wondering if this is something that should be included in the middleware? Here is what I currently have 
<img width="853" alt="Screen Shot 2022-03-07 at 11 04 30 PM" src="https://user-images.githubusercontent.com/7998380/157169772-5e7cae04-9951-4228-a24d-9e3f8b6ea29e.png">

**Comment by skyfe79** [comment]
@DistroDan 
Hi! DistroDan. First of all, thanks for your great feedback. I've updated an example to show the loading state with ProgressView.  There is no need to use middleware for async operation.  I think this PR could help you. https://github.com/ReactComponentKit/ReduxCounter/pull/1

```swift
func fetchContentValue() async { 
    do {
        commit(mutation: SET_IS_LOADING, payload: true)
        let (data, _) = try await URLSession.shared.data(from: URL(string: "https://www.facebook.com")!)
        let value = String(data: data, encoding: .utf8) ?? ""
        commit(mutation: SET_ERROR, payload: nil)
        commit(mutation: SET_CONTENT_VALUE, payload: value)
        commit(mutation: SET_IS_LOADING, payload: false)
    } catch {
        commit(mutation: SET_IS_LOADING, payload: false)
        commit(mutation: SET_ERROR, payload: error.localizedDescription)
    }
}
```

`fetchContentValue()` method setted the isLoading state when start async operation and finished it. 
ContentStore reflects the isLoading state to isLoading Publisher on the computed method of ContentStore and ComposeAppStore reflect isLoading Publisher to ProgressUI View. 

It is important to chain the publishers when you composing stores on SwiftUI.  

Thanks & best regards,

**Comment by DistroDan** [comment]
@skyfe79 Thanks so much. This is a great example and is exactly what I needed. 

Regards

**Comment by skyfe79** [comment]
@DistroDan Great Thanks! 😄
